# MGNREGA DESCRIPTIVE ANALYSIS STUDY

### DATA PREPROCESSING

### IMPORTING NECESSARY LIBRARY AND LOADING THE DATASET

In [29]:
import pandas as pd
import numpy as np
data = pd.read_csv("D:\\MERGED_SET.csv")
data.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,15623529,198.180663,48,10878,...,519227,1218221,130223,34032.16018,10985218,57,76.08,74.11,105.71,NaN
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,10931309,201.456988,50,3235,...,615947,1261092,142535,23643.54208,7152274,64,64.26,61.55,106.40,NaN
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,9831635,206.466248,59,4022,...,567546,1164238,137615,27883.60743,8591158,68,70.41,73.29,107.61,NaN
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,17114336,197.734116,46,9108,...,577694,1309583,89937,33824.03204,11557724,60,77.73,77.34,103.85,NaN
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,14897034,196.608709,46,10772,...,517720,1217417,120755,32315.21691,10553260,55,80.80,79.72,105.49,NaN

In [31]:
data.shape

(72576, 36)

### CREATING A COPY OF DATASET FOR PREPROCESSING

In [34]:
df = data.copy()

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72576 entries, 0 to 72575
Data columns (total 36 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   fin_year                                               72576 non-null  object
 1   month                                                  72576 non-null  object
 2   state_code                                             72576 non-null  int64
 3   state_name                                             72576 non-null  object
 4   district_code                                          72576 non-null  int64
 5   district_name                                          72576 non-null  object
 6   Approved_Labour_Budget                                 72576 non-null  int64
 7   Average_Wage_rate_per_day_per_person                   72576 non-null  float64
 8   Average_days_of_employment_provided_per_Household      72576 non-null  int64
 9   Differently_abled_persons_worked                       72576 non-null  int64
 10  Material_and_skilled_Wages                             72576 non-null  float64
 11  Number_of_Completed_Works                              72576 non-null  int64
 12  Number_of_GPs_with_NIL_exp                             72576 non-null  int64
 13  Number_of_Ongoing_Works                                72576 non-null  int64
 14  Persondays_of_Central_Liability_so_far                 72576 non-null  int64
 15  SC_persondays                                          72576 non-null  int64
 16  SC_workers_against_active_workers                      72576 non-null  int64
 17  ST_persondays                                          72576 non-null  int64
 18  ST_workers_against_active_workers                      72576 non-null  int64
 19  Total_Adm_Expenditure                                  72576 non-null  float64
 20  Total_Exp                                              72576 non-null  float64
 21  Total_Households_Worked                                72576 non-null  int64
 22  Total_Individuals_Worked                               72576 non-null  int64
 23  Total_No_of_Active_Job_Cards                           72576 non-null  int64
 24  Total_No_of_Active_Workers                             72576 non-null  int64
 25  Total_No_of_HHs_completed_100_Days_of_Wage_Employment  72576 non-null  int64
 26  Total_No_of_JobCards_issued                            72576 non-null  int64
 27  Total_No_of_Workers                                    72576 non-null  int64
 28  Total_No_of_Works_Takenup                              72576 non-null  int64
 29  Wages                                                  72576 non-null  float64
 30  Women_Persondays                                       72576 non-null  int64
 31  percent_of_Category_B_Works                            72576 non-null  int64
 32  percent_of_Expenditure_on_Agriculture_Allied_Works     72576 non-null  float64
 33  percent_of_NRM_Expenditure                             72576 non-null  float64
 34  percentage_payments_gererated_within_15_days           72576 non-null  float64
 35  Remarks                                                0 non-null      float64
dtypes: float64(9), int64(23), object(4)
memory usage: 19.9+ MB

In [38]:
df.describe()

,state_code,district_code,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,Material_and_skilled_Wages,Number_of_Completed_Works,Number_of_GPs_with_NIL_exp,Number_of_Ongoing_Works,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
count,72576.000000,72576.000000,7.257600e+04,7.257600e+04,72576.000000,72576.000000,72576.000000,72576.000000,72576.000000,72576.000000,...,7.257600e+04,7.257600e+04,72576.000000,72576.000000,7.257600e+04,72576.000000,72576.000000,72576.000000,72576.000000,0.0
mean,12.667232,1286.831335,3.376134e+06,5.994553e+02,33.153673,713.238178,2705.121257,6723.091049,20.809951,22090.785576,...,2.929965e+05,5.333932e+05,28813.876626,7609.887556,1.861638e+06,66.838156,45.819927,32.898009,102.185732,NaN
std,8.772118,878.017127,3.383756e+06,4.697495e+04,12.176297,1272.856645,3978.939686,8189.723808,72.123163,16690.721609,...,1.664970e+05,3.193508e+05,20905.576986,8338.031018,2.350214e+06,19.365731,21.544289,25.387296,14.387393,NaN
min,2.000000,201.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,328.000000,...,3.061300e+04,5.114600e+04,437.000000,0.000000,0.000000e+00,9.000000,0.000000,0.000000,0.000000,NaN
25%,4.000000,427.000000,1.102631e+06,2.137593e+02,25.000000,76.000000,239.968969,1645.000000,0.000000,10118.750000,...,1.700180e+05,3.083010e+05,14036.750000,1912.880648,3.638892e+05,51.000000,28.020000,7.960000,99.920000,NaN
50%,17.000000,1710.000000,2.359100e+06,2.433290e+02,34.000000,207.000000,1268.955034,4120.000000,2.000000,18159.000000,...,2.583085e+05,4.678530e+05,24526.000000,4767.177172,9.789740e+05,69.000000,43.730000,29.920000,99.990000,NaN
75%,18.000000,1815.000000,4.579258e+06,2.560312e+02,41.000000,637.000000,3526.214592,8670.000000,10.000000,30043.000000,...,3.747528e+05,6.551980e+05,38625.250000,10453.030673,2.472384e+06,83.000000,62.950000,54.210000,100.560000,NaN
max,27.000000,2733.000000,3.542998e+07,8.851511e+06,105.000000,11967.000000,54456.352830,104411.000000,1314.000000,185944.000000,...,1.151004e+06,2.070883e+06,222435.000000,79733.728990,2.296429e+07,97.000000,100.000000,100.000000,516.800000,NaN

### CHECKING FOR NULL VALUES

In [41]:
df.isna().sum()

fin_year                                                     0
month                                                        0
state_code                                                   0
state_name                                                   0
district_code                                                0
district_name                                                0
Approved_Labour_Budget                                       0
Average_Wage_rate_per_day_per_person                         0
Average_days_of_employment_provided_per_Household            0
Differently_abled_persons_worked                             0
Material_and_skilled_Wages                                   0
Number_of_Completed_Works                                    0
Number_of_GPs_with_NIL_exp                                   0
Number_of_Ongoing_Works                                      0
Persondays_of_Central_Liability_so_far                       0
SC_persondays                                                0
SC_workers_against_active_workers                            0
ST_persondays                                                0
ST_workers_against_active_workers                            0
Total_Adm_Expenditure                                        0
Total_Exp                                                    0
Total_Households_Worked                                      0
Total_Individuals_Worked                                     0
Total_No_of_Active_Job_Cards                                 0
Total_No_of_Active_Workers                                   0
Total_No_of_HHs_completed_100_Days_of_Wage_Employment        0
Total_No_of_JobCards_issued                                  0
Total_No_of_Workers                                          0
Total_No_of_Works_Takenup                                    0
Wages                                                        0
Women_Persondays                                             0
percent_of_Category_B_Works                                  0
percent_of_Expenditure_on_Agriculture_Allied_Works           0
percent_of_NRM_Expenditure                                   0
percentage_payments_gererated_within_15_days                 0
Remarks                                                  72576
dtype: int64

### CHECKING FOR ZERO VALUES

In [44]:
zero_counts = (df == 0).sum().sort_values(ascending=False)
zero_counts

Number_of_GPs_with_NIL_exp                               27233
Total_Adm_Expenditure                                    17778
Total_No_of_HHs_completed_100_Days_of_Wage_Employment     9777
Material_and_skilled_Wages                                5539
percent_of_NRM_Expenditure                                 774
Differently_abled_persons_worked                           544
ST_persondays                                              101
Approved_Labour_Budget                                      72
percentage_payments_gererated_within_15_days                35
SC_persondays                                               31
percent_of_Expenditure_on_Agriculture_Allied_Works          26
Number_of_Completed_Works                                   16
Average_Wage_rate_per_day_per_person                        16
Women_Persondays                                            15
Persondays_of_Central_Liability_so_far                      15
Total_Households_Worked                                     15
Average_days_of_employment_provided_per_Household           15
Total_Individuals_Worked                                    15
Wages                                                        5
Total_Exp                                                    3
Total_No_of_Workers                                          0
fin_year                                                     0
Total_No_of_Works_Takenup                                    0
percent_of_Category_B_Works                                  0
Total_No_of_JobCards_issued                                  0
ST_workers_against_active_workers                            0
Total_No_of_Active_Workers                                   0
Total_No_of_Active_Job_Cards                                 0
month                                                        0
SC_workers_against_active_workers                            0
Number_of_Ongoing_Works                                      0
district_name                                                0
district_code                                                0
state_name                                                   0
state_code                                                   0
Remarks                                                      0
dtype: int64

### REPLACING ZERO VALUES WITH NAN

In [47]:
df['Approved_Labour_Budget'] = df['Approved_Labour_Budget'].replace(0, np.nan)

df['Average_Wage_rate_per_day_per_person'] = df['Average_Wage_rate_per_day_per_person'].replace(0, np.nan)

In [49]:
df

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,15623529.0,198.180663,48,10878,...,519227,1218221,130223,34032.160180,10985218,57,76.08,74.11,105.71,NaN
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,10931309.0,201.456988,50,3235,...,615947,1261092,142535,23643.542080,7152274,64,64.26,61.55,106.40,NaN
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,9831635.0,206.466248,59,4022,...,567546,1164238,137615,27883.607430,8591158,68,70.41,73.29,107.61,NaN
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,17114336.0,197.734116,46,9108,...,577694,1309583,89937,33824.032040,11557724,60,77.73,77.34,103.85,NaN
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,14897034.0,196.608709,46,10772,...,517720,1217417,120755,32315.216910,10553260,55,80.80,79.72,105.49,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72571,2024-2025,Oct,27,RAJASTHAN,2717,BARMER,18631150.0,270.782015,52,1037,...,686454,1304481,140259,46448.874530,9583665,92,76.84,7.20,99.98,NaN
72572,2024-2025,Nov,27,RAJASTHAN,2721,AJMER,12881389.0,198.759421,35,948,...,490517,870704,20818,20412.300370,8388305,23,26.59,45.44,99.98,NaN
72573,2024-2025,July,27,RAJASTHAN,2725,RAJSAMAND,5590233.0,204.380049,34,771,...,249121,452500,9705,8250.430165,3463537,29,22.62,63.86,99.98,NaN
72574,2024-2025,Nov,27,RAJASTHAN,2721,AJMER,12881389.0,198.752452,35,944,...,490385,870456,20573,20185.974750,8291778,23,26.92,45.59,99.98,NaN
72575,2024-2025,Nov,27,RAJASTHAN,2727,DUNGARPUR,12747862.0,218.104874,53,5313,...,409371,803543,38298,37994.883160,12539770,35,15.05,51.89,99.98,NaN

In [57]:
mean_budget = df.groupby(['state_name','fin_year'])['Approved_Labour_Budget'].transform('mean')

df['Approved_Labour_Budget'] = df['Approved_Labour_Budget'].fillna(mean_budget)

In [59]:
mean_wage = df.groupby(['state_name','fin_year'])['Average_Wage_rate_per_day_per_person'].transform('mean')

df['Average_Wage_rate_per_day_per_person'] = df['Average_Wage_rate_per_day_per_person'].fillna(mean_wage)

In [61]:
(df['Approved_Labour_Budget'] == 0).sum()

(df['Average_Wage_rate_per_day_per_person'] == 0).sum()

0

### CONVERTING DATATYPES

In [64]:
df['fin_year'] = df['fin_year'].astype(str)
df['state_name'] = df['state_name'].astype('category')
df['district_name'] = df['district_name'].astype('category')
df['month'] = pd.Categorical(df['month'], 
                              categories=['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
                              ordered=True)

In [66]:
df.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,15623529.0,198.180663,48,10878,...,519227,1218221,130223,34032.16018,10985218,57,76.08,74.11,105.71,NaN
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,10931309.0,201.456988,50,3235,...,615947,1261092,142535,23643.54208,7152274,64,64.26,61.55,106.40,NaN
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,9831635.0,206.466248,59,4022,...,567546,1164238,137615,27883.60743,8591158,68,70.41,73.29,107.61,NaN
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,17114336.0,197.734116,46,9108,...,577694,1309583,89937,33824.03204,11557724,60,77.73,77.34,103.85,NaN
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,14897034.0,196.608709,46,10772,...,517720,1217417,120755,32315.21691,10553260,55,80.80,79.72,105.49,NaN

In [68]:
df.shape

(72576, 36)

### CHECKING FOR DUPLICATES

In [71]:
df.duplicated().sum()

4

In [73]:
df = df.drop_duplicates()

In [75]:
df.duplicated().sum()

0

In [77]:
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (72572, 36)

In [79]:
df.describe()

,state_code,district_code,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,Material_and_skilled_Wages,Number_of_Completed_Works,Number_of_GPs_with_NIL_exp,Number_of_Ongoing_Works,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
count,72572.000000,72572.000000,7.257200e+04,7.257200e+04,72572.000000,72572.000000,72572.000000,72572.000000,72572.000000,72572.000000,...,7.257200e+04,7.257200e+04,72572.000000,72572.000000,7.257200e+04,72572.000000,72572.000000,72572.000000,72572.000000,0.0
mean,12.667379,1286.846924,3.377457e+06,5.996732e+02,33.153599,713.269512,2705.259362,6723.405528,20.810533,22091.370088,...,2.930081e+05,5.334144e+05,28814.775616,7610.196680,1.861715e+06,66.837995,45.820244,32.897017,102.185829,NaN
std,8.772136,878.018675,3.382823e+06,4.697625e+04,12.176465,1272.884644,3979.005761,8189.838628,72.125062,16690.936638,...,1.664938e+05,3.193461e+05,20905.745311,8338.151843,2.350254e+06,19.366117,21.543067,25.385456,14.387783,NaN
min,2.000000,201.000000,1.000000e+00,6.415512e-01,0.000000,0.000000,0.000000,0.000000,0.000000,328.000000,...,3.061300e+04,5.114600e+04,437.000000,0.000000,0.000000e+00,9.000000,0.000000,0.000000,0.000000,NaN
25%,4.000000,427.000000,1.105220e+06,2.137771e+02,25.000000,76.000000,239.968969,1645.000000,0.000000,10119.000000,...,1.700305e+05,3.083198e+05,14037.000000,1912.914124,3.638970e+05,51.000000,28.020000,7.960000,99.920000,NaN
50%,17.000000,1710.000000,2.359377e+06,2.433350e+02,34.000000,207.000000,1268.958333,4120.500000,2.000000,18160.000000,...,2.583185e+05,4.678595e+05,24527.500000,4767.464128,9.790525e+05,69.000000,43.730000,29.920000,99.990000,NaN
75%,18.000000,1815.000000,4.579258e+06,2.560487e+02,41.000000,637.000000,3526.214592,8670.500000,10.000000,30043.000000,...,3.747675e+05,6.551998e+05,38626.000000,10453.524487,2.472444e+06,83.000000,62.950000,54.202500,100.560000,NaN
max,27.000000,2733.000000,3.542998e+07,8.851511e+06,105.000000,11967.000000,54456.352830,104411.000000,1314.000000,185944.000000,...,1.151004e+06,2.070883e+06,222435.000000,79733.728990,2.296429e+07,97.000000,100.000000,100.000000,516.800000,NaN

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72572 entries, 0 to 72575
Data columns (total 36 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   fin_year                                               72572 non-null  object
 1   month                                                  49227 non-null  category
 2   state_code                                             72572 non-null  int64
 3   state_name                                             72572 non-null  category
 4   district_code                                          72572 non-null  int64
 5   district_name                                          72572 non-null  category
 6   Approved_Labour_Budget                                 72572 non-null  float64
 7   Average_Wage_rate_per_day_per_person                   72572 non-null  float64
 8   Average_days_of_employment_provided_per_Household      72572 non-null  int64
 9   Differently_abled_persons_worked                       72572 non-null  int64
 10  Material_and_skilled_Wages                             72572 non-null  float64
 11  Number_of_Completed_Works                              72572 non-null  int64
 12  Number_of_GPs_with_NIL_exp                             72572 non-null  int64
 13  Number_of_Ongoing_Works                                72572 non-null  int64
 14  Persondays_of_Central_Liability_so_far                 72572 non-null  int64
 15  SC_persondays                                          72572 non-null  int64
 16  SC_workers_against_active_workers                      72572 non-null  int64
 17  ST_persondays                                          72572 non-null  int64
 18  ST_workers_against_active_workers                      72572 non-null  int64
 19  Total_Adm_Expenditure                                  72572 non-null  float64
 20  Total_Exp                                              72572 non-null  float64
 21  Total_Households_Worked                                72572 non-null  int64
 22  Total_Individuals_Worked                               72572 non-null  int64
 23  Total_No_of_Active_Job_Cards                           72572 non-null  int64
 24  Total_No_of_Active_Workers                             72572 non-null  int64
 25  Total_No_of_HHs_completed_100_Days_of_Wage_Employment  72572 non-null  int64
 26  Total_No_of_JobCards_issued                            72572 non-null  int64
 27  Total_No_of_Workers                                    72572 non-null  int64
 28  Total_No_of_Works_Takenup                              72572 non-null  int64
 29  Wages                                                  72572 non-null  float64
 30  Women_Persondays                                       72572 non-null  int64
 31  percent_of_Category_B_Works                            72572 non-null  int64
 32  percent_of_Expenditure_on_Agriculture_Allied_Works     72572 non-null  float64
 33  percent_of_NRM_Expenditure                             72572 non-null  float64
 34  percentage_payments_gererated_within_15_days           72572 non-null  float64
 35  Remarks                                                0 non-null      float64
dtypes: category(3), float64(10), int64(22), object(1)
memory usage: 19.1+ MB