# MGNREGA DESCRIPTIVE ANALYSIS STUDY

### DATA PREPROCESSING

### IMPORTING NECESSARY LIBRARY AND LOADING THE DATASET

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("D:\\MERGED_SET.csv")
data.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,15623529,198.180663,48,10878,...,519227,1218221,130223,34032.16018,10985218,57,76.08,74.11,105.71,NaN
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,10931309,201.456988,50,3235,...,615947,1261092,142535,23643.54208,7152274,64,64.26,61.55,106.40,NaN
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,9831635,206.466248,59,4022,...,567546,1164238,137615,27883.60743,8591158,68,70.41,73.29,107.61,NaN
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,17114336,197.734116,46,9108,...,577694,1309583,89937,33824.03204,11557724,60,77.73,77.34,103.85,NaN
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,14897034,196.608709,46,10772,...,517720,1217417,120755,32315.21691,10553260,55,80.80,79.72,105.49,NaN

In [2]:
data.shape

(72576, 36)

### CREATING A COPY OF DATASET FOR PREPROCESSING

In [3]:
df = data.copy()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72576 entries, 0 to 72575
Data columns (total 36 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   fin_year                                               72576 non-null  object
 1   month                                                  72576 non-null  object
 2   state_code                                             72576 non-null  int64
 3   state_name                                             72576 non-null  object
 4   district_code                                          72576 non-null  int64
 5   district_name                                          72576 non-null  object
 6   Approved_Labour_Budget                                 72576 non-null  int64
 7   Average_Wage_rate_per_day_per_person                   72576 non-null  float64
 8   Average_days_of_employment_provided_per_Household      72576 non-null  int64
 9   Differently_abled_persons_worked                       72576 non-null  int64
 10  Material_and_skilled_Wages                             72576 non-null  float64
 11  Number_of_Completed_Works                              72576 non-null  int64
 12  Number_of_GPs_with_NIL_exp                             72576 non-null  int64
 13  Number_of_Ongoing_Works                                72576 non-null  int64
 14  Persondays_of_Central_Liability_so_far                 72576 non-null  int64
 15  SC_persondays                                          72576 non-null  int64
 16  SC_workers_against_active_workers                      72576 non-null  int64
 17  ST_persondays                                          72576 non-null  int64
 18  ST_workers_against_active_workers                      72576 non-null  int64
 19  Total_Adm_Expenditure                                  72576 non-null  float64
 20  Total_Exp                                              72576 non-null  float64
 21  Total_Households_Worked                                72576 non-null  int64
 22  Total_Individuals_Worked                               72576 non-null  int64
 23  Total_No_of_Active_Job_Cards                           72576 non-null  int64
 24  Total_No_of_Active_Workers                             72576 non-null  int64
 25  Total_No_of_HHs_completed_100_Days_of_Wage_Employment  72576 non-null  int64
 26  Total_No_of_JobCards_issued                            72576 non-null  int64
 27  Total_No_of_Workers                                    72576 non-null  int64
 28  Total_No_of_Works_Takenup                              72576 non-null  int64
 29  Wages                                                  72576 non-null  float64
 30  Women_Persondays                                       72576 non-null  int64
 31  percent_of_Category_B_Works                            72576 non-null  int64
 32  percent_of_Expenditure_on_Agriculture_Allied_Works     72576 non-null  float64
 33  percent_of_NRM_Expenditure                             72576 non-null  float64
 34  percentage_payments_gererated_within_15_days           72576 non-null  float64
 35  Remarks                                                0 non-null      float64
dtypes: float64(9), int64(23), object(4)
memory usage: 19.9+ MB

In [5]:
df.describe()

,state_code,district_code,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,Material_and_skilled_Wages,Number_of_Completed_Works,Number_of_GPs_with_NIL_exp,Number_of_Ongoing_Works,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
count,72576.000000,72576.000000,7.257600e+04,7.257600e+04,72576.000000,72576.000000,72576.000000,72576.000000,72576.000000,72576.000000,...,7.257600e+04,7.257600e+04,72576.000000,72576.000000,7.257600e+04,72576.000000,72576.000000,72576.000000,72576.000000,0.0
mean,12.667232,1286.831335,3.376134e+06,5.994553e+02,33.153673,713.238178,2705.121257,6723.091049,20.809951,22090.785576,...,2.929965e+05,5.333932e+05,28813.876626,7609.887556,1.861638e+06,66.838156,45.819927,32.898009,102.185732,NaN
std,8.772118,878.017127,3.383756e+06,4.697495e+04,12.176297,1272.856645,3978.939686,8189.723808,72.123163,16690.721609,...,1.664970e+05,3.193508e+05,20905.576986,8338.031018,2.350214e+06,19.365731,21.544289,25.387296,14.387393,NaN
min,2.000000,201.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,328.000000,...,3.061300e+04,5.114600e+04,437.000000,0.000000,0.000000e+00,9.000000,0.000000,0.000000,0.000000,NaN
25%,4.000000,427.000000,1.102631e+06,2.137593e+02,25.000000,76.000000,239.968969,1645.000000,0.000000,10118.750000,...,1.700180e+05,3.083010e+05,14036.750000,1912.880648,3.638892e+05,51.000000,28.020000,7.960000,99.920000,NaN
50%,17.000000,1710.000000,2.359100e+06,2.433290e+02,34.000000,207.000000,1268.955034,4120.000000,2.000000,18159.000000,...,2.583085e+05,4.678530e+05,24526.000000,4767.177172,9.789740e+05,69.000000,43.730000,29.920000,99.990000,NaN
75%,18.000000,1815.000000,4.579258e+06,2.560312e+02,41.000000,637.000000,3526.214592,8670.000000,10.000000,30043.000000,...,3.747528e+05,6.551980e+05,38625.250000,10453.030673,2.472384e+06,83.000000,62.950000,54.210000,100.560000,NaN
max,27.000000,2733.000000,3.542998e+07,8.851511e+06,105.000000,11967.000000,54456.352830,104411.000000,1314.000000,185944.000000,...,1.151004e+06,2.070883e+06,222435.000000,79733.728990,2.296429e+07,97.000000,100.000000,100.000000,516.800000,NaN

### CHECKING FOR NULL VALUES

In [6]:
df.isna().sum()

fin_year                                                     0
month                                                        0
state_code                                                   0
state_name                                                   0
district_code                                                0
district_name                                                0
Approved_Labour_Budget                                       0
Average_Wage_rate_per_day_per_person                         0
Average_days_of_employment_provided_per_Household            0
Differently_abled_persons_worked                             0
Material_and_skilled_Wages                                   0
Number_of_Completed_Works                                    0
Number_of_GPs_with_NIL_exp                                   0
Number_of_Ongoing_Works                                      0
Persondays_of_Central_Liability_so_far                       0
SC_persondays                                                0
SC_workers_against_active_workers                            0
ST_persondays                                                0
ST_workers_against_active_workers                            0
Total_Adm_Expenditure                                        0
Total_Exp                                                    0
Total_Households_Worked                                      0
Total_Individuals_Worked                                     0
Total_No_of_Active_Job_Cards                                 0
Total_No_of_Active_Workers                                   0
Total_No_of_HHs_completed_100_Days_of_Wage_Employment        0
Total_No_of_JobCards_issued                                  0
Total_No_of_Workers                                          0
Total_No_of_Works_Takenup                                    0
Wages                                                        0
Women_Persondays                                             0
percent_of_Category_B_Works                                  0
percent_of_Expenditure_on_Agriculture_Allied_Works           0
percent_of_NRM_Expenditure                                   0
percentage_payments_gererated_within_15_days                 0
Remarks                                                  72576
dtype: int64

### CHECKING FOR ZERO VALUES

In [7]:
zero_counts = (df == 0).sum().sort_values(ascending=False)
zero_counts

Number_of_GPs_with_NIL_exp                               27233
Total_Adm_Expenditure                                    17778
Total_No_of_HHs_completed_100_Days_of_Wage_Employment     9777
Material_and_skilled_Wages                                5539
percent_of_NRM_Expenditure                                 774
Differently_abled_persons_worked                           544
ST_persondays                                              101
Approved_Labour_Budget                                      72
percentage_payments_gererated_within_15_days                35
SC_persondays                                               31
percent_of_Expenditure_on_Agriculture_Allied_Works          26
Average_Wage_rate_per_day_per_person                        16
Number_of_Completed_Works                                   16
Total_Households_Worked                                     15
Average_days_of_employment_provided_per_Household           15
Women_Persondays                                            15
Total_Individuals_Worked                                    15
Persondays_of_Central_Liability_so_far                      15
Wages                                                        5
Total_Exp                                                    3
state_name                                                   0
state_code                                                   0
month                                                        0
fin_year                                                     0
district_code                                                0
SC_workers_against_active_workers                            0
Number_of_Ongoing_Works                                      0
district_name                                                0
ST_workers_against_active_workers                            0
Total_No_of_JobCards_issued                                  0
Total_No_of_Active_Workers                                   0
Total_No_of_Active_Job_Cards                                 0
Total_No_of_Workers                                          0
Total_No_of_Works_Takenup                                    0
percent_of_Category_B_Works                                  0
Remarks                                                      0
dtype: int64

### REPLACING ZERO VALUES WITH NAN

In [8]:
df['Approved_Labour_Budget'] = df['Approved_Labour_Budget'].replace(0, np.nan)

df['Average_Wage_rate_per_day_per_person'] = df['Average_Wage_rate_per_day_per_person'].replace(0, np.nan)

Zero values were treated only in the Approved Labour Budget and Average Wage Rate per Day per Person variables because such values cannot logically be zero in the context of MGNREGA implementation and are likely to represent missing or inaccurately recorded data. 

In contrast, zero values in other variables may indicate genuine absence of activity during a particular period.
Therefore, they were retained to maintain the accuracy and integrity of the dataset.

In [9]:
df

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,15623529.0,198.180663,48,10878,...,519227,1218221,130223,34032.160180,10985218,57,76.08,74.11,105.71,NaN
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,10931309.0,201.456988,50,3235,...,615947,1261092,142535,23643.542080,7152274,64,64.26,61.55,106.40,NaN
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,9831635.0,206.466248,59,4022,...,567546,1164238,137615,27883.607430,8591158,68,70.41,73.29,107.61,NaN
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,17114336.0,197.734116,46,9108,...,577694,1309583,89937,33824.032040,11557724,60,77.73,77.34,103.85,NaN
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,14897034.0,196.608709,46,10772,...,517720,1217417,120755,32315.216910,10553260,55,80.80,79.72,105.49,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72571,2024-2025,Oct,27,RAJASTHAN,2717,BARMER,18631150.0,270.782015,52,1037,...,686454,1304481,140259,46448.874530,9583665,92,76.84,7.20,99.98,NaN
72572,2024-2025,Nov,27,RAJASTHAN,2721,AJMER,12881389.0,198.759421,35,948,...,490517,870704,20818,20412.300370,8388305,23,26.59,45.44,99.98,NaN
72573,2024-2025,July,27,RAJASTHAN,2725,RAJSAMAND,5590233.0,204.380049,34,771,...,249121,452500,9705,8250.430165,3463537,29,22.62,63.86,99.98,NaN
72574,2024-2025,Nov,27,RAJASTHAN,2721,AJMER,12881389.0,198.752452,35,944,...,490385,870456,20573,20185.974750,8291778,23,26.92,45.59,99.98,NaN
72575,2024-2025,Nov,27,RAJASTHAN,2727,DUNGARPUR,12747862.0,218.104874,53,5313,...,409371,803543,38298,37994.883160,12539770,35,15.05,51.89,99.98,NaN

### FILLING MISSING VALUES

In [10]:
mean_budget = df.groupby(['state_name','fin_year'])['Approved_Labour_Budget'].transform('mean')

df['Approved_Labour_Budget'] = df['Approved_Labour_Budget'].fillna(mean_budget)

In [11]:
mean_wage = df.groupby(['state_name','fin_year'])['Average_Wage_rate_per_day_per_person'].transform('mean')

df['Average_Wage_rate_per_day_per_person'] = df['Average_Wage_rate_per_day_per_person'].fillna(mean_wage)

The missing values are replaced with group mean.

### CONFIRMING NO ZERO VALUES

In [12]:
(df['Approved_Labour_Budget'] == 0).sum()

(df['Average_Wage_rate_per_day_per_person'] == 0).sum()

np.int64(0)

### CONVERTING DATATYPES

In [13]:
df['fin_year'] = df['fin_year'].astype('category')
df['state_name'] = df['state_name'].astype('category')
df['district_name'] = df['district_name'].astype('category')
df['month'] = pd.Categorical(df['month'], 
                              categories=['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'],
                              ordered=True)

Converting object columns to categorical datatype reduces memory usage and speeds up groupby/pivot operations.

Month ordering ensures correct time-series analysis.

In [14]:
df.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,15623529.0,198.180663,48,10878,...,519227,1218221,130223,34032.16018,10985218,57,76.08,74.11,105.71,NaN
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,10931309.0,201.456988,50,3235,...,615947,1261092,142535,23643.54208,7152274,64,64.26,61.55,106.40,NaN
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,9831635.0,206.466248,59,4022,...,567546,1164238,137615,27883.60743,8591158,68,70.41,73.29,107.61,NaN
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,17114336.0,197.734116,46,9108,...,577694,1309583,89937,33824.03204,11557724,60,77.73,77.34,103.85,NaN
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,14897034.0,196.608709,46,10772,...,517720,1217417,120755,32315.21691,10553260,55,80.80,79.72,105.49,NaN

In [15]:
df.shape

(72576, 36)

### CHECKING FOR DUPLICATES

In [16]:
df.duplicated().sum()

np.int64(4)

In [17]:
df = df.drop_duplicates()

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (72572, 36)

Duplicate validation was performed across all columns.
Four fully identical entries were detected and removed to ensure data integrity.

In [20]:
df.describe()

,state_code,district_code,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,Material_and_skilled_Wages,Number_of_Completed_Works,Number_of_GPs_with_NIL_exp,Number_of_Ongoing_Works,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
count,72572.000000,72572.000000,7.257200e+04,7.257200e+04,72572.000000,72572.000000,72572.000000,72572.000000,72572.000000,72572.000000,...,7.257200e+04,7.257200e+04,72572.000000,72572.000000,7.257200e+04,72572.000000,72572.000000,72572.000000,72572.000000,0.0
mean,12.667379,1286.846924,3.377457e+06,5.996732e+02,33.153599,713.269512,2705.259362,6723.405528,20.810533,22091.370088,...,2.930081e+05,5.334144e+05,28814.775616,7610.196680,1.861715e+06,66.837995,45.820244,32.897017,102.185829,NaN
std,8.772136,878.018675,3.382823e+06,4.697625e+04,12.176465,1272.884644,3979.005761,8189.838628,72.125062,16690.936638,...,1.664938e+05,3.193461e+05,20905.745311,8338.151843,2.350254e+06,19.366117,21.543067,25.385456,14.387783,NaN
min,2.000000,201.000000,1.000000e+00,6.415512e-01,0.000000,0.000000,0.000000,0.000000,0.000000,328.000000,...,3.061300e+04,5.114600e+04,437.000000,0.000000,0.000000e+00,9.000000,0.000000,0.000000,0.000000,NaN
25%,4.000000,427.000000,1.105220e+06,2.137771e+02,25.000000,76.000000,239.968969,1645.000000,0.000000,10119.000000,...,1.700305e+05,3.083198e+05,14037.000000,1912.914124,3.638970e+05,51.000000,28.020000,7.960000,99.920000,NaN
50%,17.000000,1710.000000,2.359377e+06,2.433350e+02,34.000000,207.000000,1268.958333,4120.500000,2.000000,18160.000000,...,2.583185e+05,4.678595e+05,24527.500000,4767.464128,9.790525e+05,69.000000,43.730000,29.920000,99.990000,NaN
75%,18.000000,1815.000000,4.579258e+06,2.560487e+02,41.000000,637.000000,3526.214592,8670.500000,10.000000,30043.000000,...,3.747675e+05,6.551998e+05,38626.000000,10453.524487,2.472444e+06,83.000000,62.950000,54.202500,100.560000,NaN
max,27.000000,2733.000000,3.542998e+07,8.851511e+06,105.000000,11967.000000,54456.352830,104411.000000,1314.000000,185944.000000,...,1.151004e+06,2.070883e+06,222435.000000,79733.728990,2.296429e+07,97.000000,100.000000,100.000000,516.800000,NaN

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72572 entries, 0 to 72575
Data columns (total 36 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   fin_year                                               72572 non-null  category
 1   month                                                  49227 non-null  category
 2   state_code                                             72572 non-null  int64
 3   state_name                                             72572 non-null  category
 4   district_code                                          72572 non-null  int64
 5   district_name                                          72572 non-null  category
 6   Approved_Labour_Budget                                 72572 non-null  float64
 7   Average_Wage_rate_per_day_per_person                   72572 non-null  float64
 8   Average_days_of_employment_provided_per_Household      72572 non-null  int64
 9   Differently_abled_persons_worked                       72572 non-null  int64
 10  Material_and_skilled_Wages                             72572 non-null  float64
 11  Number_of_Completed_Works                              72572 non-null  int64
 12  Number_of_GPs_with_NIL_exp                             72572 non-null  int64
 13  Number_of_Ongoing_Works                                72572 non-null  int64
 14  Persondays_of_Central_Liability_so_far                 72572 non-null  int64
 15  SC_persondays                                          72572 non-null  int64
 16  SC_workers_against_active_workers                      72572 non-null  int64
 17  ST_persondays                                          72572 non-null  int64
 18  ST_workers_against_active_workers                      72572 non-null  int64
 19  Total_Adm_Expenditure                                  72572 non-null  float64
 20  Total_Exp                                              72572 non-null  float64
 21  Total_Households_Worked                                72572 non-null  int64
 22  Total_Individuals_Worked                               72572 non-null  int64
 23  Total_No_of_Active_Job_Cards                           72572 non-null  int64
 24  Total_No_of_Active_Workers                             72572 non-null  int64
 25  Total_No_of_HHs_completed_100_Days_of_Wage_Employment  72572 non-null  int64
 26  Total_No_of_JobCards_issued                            72572 non-null  int64
 27  Total_No_of_Workers                                    72572 non-null  int64
 28  Total_No_of_Works_Takenup                              72572 non-null  int64
 29  Wages                                                  72572 non-null  float64
 30  Women_Persondays                                       72572 non-null  int64
 31  percent_of_Category_B_Works                            72572 non-null  int64
 32  percent_of_Expenditure_on_Agriculture_Allied_Works     72572 non-null  float64
 33  percent_of_NRM_Expenditure                             72572 non-null  float64
 34  percentage_payments_gererated_within_15_days           72572 non-null  float64
 35  Remarks                                                0 non-null      float64
dtypes: category(4), float64(10), int64(22)
memory usage: 18.6 MB

### VERIFYING DATA TYPES

In [22]:
df.dtypes

fin_year                                                 category
month                                                    category
state_code                                                  int64
state_name                                               category
district_code                                               int64
district_name                                            category
Approved_Labour_Budget                                    float64
Average_Wage_rate_per_day_per_person                      float64
Average_days_of_employment_provided_per_Household           int64
Differently_abled_persons_worked                            int64
Material_and_skilled_Wages                                float64
Number_of_Completed_Works                                   int64
Number_of_GPs_with_NIL_exp                                  int64
Number_of_Ongoing_Works                                     int64
Persondays_of_Central_Liability_so_far                      int64
SC_persondays                                               int64
SC_workers_against_active_workers                           int64
ST_persondays                                               int64
ST_workers_against_active_workers                           int64
Total_Adm_Expenditure                                     float64
Total_Exp                                                 float64
Total_Households_Worked                                     int64
Total_Individuals_Worked                                    int64
Total_No_of_Active_Job_Cards                                int64
Total_No_of_Active_Workers                                  int64
Total_No_of_HHs_completed_100_Days_of_Wage_Employment       int64
Total_No_of_JobCards_issued                                 int64
Total_No_of_Workers                                         int64
Total_No_of_Works_Takenup                                   int64
Wages                                                     float64
Women_Persondays                                            int64
percent_of_Category_B_Works                                 int64
percent_of_Expenditure_on_Agriculture_Allied_Works        float64
percent_of_NRM_Expenditure                                float64
percentage_payments_gererated_within_15_days              float64
Remarks                                                   float64
dtype: object

### RENAMING COLUMN NAME

In [23]:
df = df.rename(columns={
    'percentage_payments_gererated_within_15_days': 
    'percentage_payments_generated_within_15_days'
})

### DROPPING EXTRA COLUMN

In [24]:
df = df.drop(columns=['Remarks'], errors='ignore')

In [25]:
print("Shape after dropping a column: ", df.shape)

Shape after dropping a column:  (72572, 35)

The Remarks column was dropped because it contains only NaN values, providing no useful information for analysis.

In [26]:
df.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_generated_within_15_days
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,15623529.0,198.180663,48,10878,...,14672,519227,1218221,130223,34032.16018,10985218,57,76.08,74.11,105.71
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,10931309.0,201.456988,50,3235,...,27632,615947,1261092,142535,23643.54208,7152274,64,64.26,61.55,106.40
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,9831635.0,206.466248,59,4022,...,40799,567546,1164238,137615,27883.60743,8591158,68,70.41,73.29,107.61
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,17114336.0,197.734116,46,9108,...,12019,577694,1309583,89937,33824.03204,11557724,60,77.73,77.34,103.85
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,14897034.0,196.608709,46,10772,...,10794,517720,1217417,120755,32315.21691,10553260,55,80.80,79.72,105.49

### DISPLAY FORMATTING

In [27]:
pd.set_option('display.float_format', '{:,.2f}'.format)

All the numbers in scientific notation, in any column, will now appear as a regular number with commas and 2 decimals.

## ADVANCED PREPROCESSING

### CREATING A SAFE WORKING COPY

In [28]:
df_clean = df.copy()

### LOGICAL RANGE VALIDATION

In [29]:
cols = ['percent_of_NRM_Expenditure',
        'percent_of_Expenditure_on_Agriculture_Allied_Works',
        'percentage_payments_generated_within_15_days']

for col in cols:
    df_clean.loc[(df_clean[col] < 0) | (df_clean[col] > 100), col] = np.nan

Checks whether values fall within valid logical ranges without removing rows.

### OUTLIER DETECTION

In [30]:
numeric_cols = df_clean.select_dtypes(include=['int64','float64']).columns

for col in numeric_cols:
    
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df_clean[(df_clean[col] < lower) | (df_clean[col] > upper)]
    
    print(f"{col} : {len(outliers)} outliers")

state_code : 0 outliers
district_code : 0 outliers
Approved_Labour_Budget : 4038 outliers
Average_Wage_rate_per_day_per_person : 5094 outliers
Average_days_of_employment_provided_per_Household : 405 outliers
Differently_abled_persons_worked : 10531 outliers
Material_and_skilled_Wages : 5196 outliers
Number_of_Completed_Works : 4952 outliers
Number_of_GPs_with_NIL_exp : 10324 outliers
Number_of_Ongoing_Works : 2209 outliers
Persondays_of_Central_Liability_so_far : 4270 outliers
SC_persondays : 6015 outliers
SC_workers_against_active_workers : 4459 outliers
ST_persondays : 8579 outliers
ST_workers_against_active_workers : 6529 outliers
Total_Adm_Expenditure : 3759 outliers
Total_Exp : 4362 outliers
Total_Households_Worked : 3299 outliers
Total_Individuals_Worked : 3994 outliers
Total_No_of_Active_Job_Cards : 2763 outliers
Total_No_of_Active_Workers : 3328 outliers
Total_No_of_HHs_completed_100_Days_of_Wage_Employment : 11181 outliers
Total_No_of_JobCards_issued : 2668 outliers
Total_No_of_Workers : 4085 outliers
Total_No_of_Works_Takenup : 2103 outliers
Wages : 4424 outliers
Women_Persondays : 5112 outliers
percent_of_Category_B_Works : 0 outliers
percent_of_Expenditure_on_Agriculture_Allied_Works : 0 outliers
percent_of_NRM_Expenditure : 0 outliers
percentage_payments_generated_within_15_days : 3205 outliers

Outliers were detected using the IQR method for all numerical variables.
However, since the dataset represents district-level administrative data, large variations across districts are expected. 
A large state district will naturally have higher expenditures and persondays.
Therefore these statistical outliers represent real extreme values rather than data errors.

Only logically impossible values (e.g., negative wages, expenditures or persondays) would be treated if present.

### TREATING LOGICALLY IMPOSSIBLE VALUES

#### 1. WAGE RATE

In [31]:
df_clean.loc[df_clean['Average_Wage_rate_per_day_per_person'] < 0,
             'Average_Wage_rate_per_day_per_person'] = np.nan
#Wage cannot be negative. If found, the values will be converted to NAN

#### 2. EXPENDITURE VARIABLE

In [32]:
exp_cols = ['Total_Exp','Total_Adm_Expenditure','Material_and_skilled_Wages','Wages']

for col in exp_cols:
    df_clean.loc[df_clean[col] < 0, col] = np.nan
#Expenditure values cannot be negative.

#### 3. PERSONDAYS AND WORKER COUNTS

In [33]:
count_cols = [
'SC_persondays','ST_persondays','Women_Persondays',
'Total_Households_Worked',
'Total_Individuals_Worked','Total_No_of_Workers'
]

for col in count_cols:
    df_clean.loc[df_clean[col] < 0, col] = np.nan
#Counts cannot be negative.

The dataset contains district-level aggregated statistics.
Large districts will naturally have:
-higher wage rate
-higher expenditure
-more persondays
-more workers
So removing statistical outliers would bias the dataset toward smaller districts. 
No rows were removed to preserve the completeness and integrity of the dataset.

### CREATING STATE-YEAR AGGREGATE DATASET

In [34]:
df_clean.columns

Index(['fin_year', 'month', 'state_code', 'state_name', 'district_code',
       'district_name', 'Approved_Labour_Budget',
       'Average_Wage_rate_per_day_per_person',
       'Average_days_of_employment_provided_per_Household',
       'Differently_abled_persons_worked', 'Material_and_skilled_Wages',
       'Number_of_Completed_Works', 'Number_of_GPs_with_NIL_exp',
       'Number_of_Ongoing_Works', 'Persondays_of_Central_Liability_so_far',
       'SC_persondays', 'SC_workers_against_active_workers', 'ST_persondays',
       'ST_workers_against_active_workers', 'Total_Adm_Expenditure',
       'Total_Exp', 'Total_Households_Worked', 'Total_Individuals_Worked',
       'Total_No_of_Active_Job_Cards', 'Total_No_of_Active_Workers',
       'Total_No_of_HHs_completed_100_Days_of_Wage_Employment',
       'Total_No_of_JobCards_issued', 'Total_No_of_Workers',
       'Total_No_of_Works_Takenup', 'Wages', 'Women_Persondays',
       'percent_of_Category_B_Works',
       'percent_of_Expenditure_on_Agriculture_Allied_Works',
       'percent_of_NRM_Expenditure',
       'percentage_payments_generated_within_15_days'],
      dtype='object')

State-Year aggregated dataset is useful for analysis, especially for:
-State comparison
-Yearly trend plots
-Policy interpretation

In [35]:
# State-year aggregation including operational performance indicators
df_state_year = df_clean.groupby(['state_name','fin_year'], as_index=False,observed=False).agg({
    
    'Total_Exp':'sum',
    'Approved_Labour_Budget':'sum',
    'Average_Wage_rate_per_day_per_person':'mean',
    'Total_Households_Worked':'sum',
    'Total_Individuals_Worked':'sum',
    'Average_days_of_employment_provided_per_Household':'mean',
    'Persondays_of_Central_Liability_so_far':'sum',
    'SC_persondays':'sum',
    'ST_persondays':'sum',
    'Women_Persondays':'sum',
    'Differently_abled_persons_worked':'sum',
    'Material_and_skilled_Wages':'sum',
    'Wages':'sum',
    'Total_Adm_Expenditure':'sum',
    'Total_No_of_HHs_completed_100_Days_of_Wage_Employment':'sum',
    'percentage_payments_generated_within_15_days':'mean',
    # Operational performance indicators
    'Number_of_Completed_Works':'sum',
    'Number_of_Ongoing_Works':'sum',
    'Total_No_of_JobCards_issued':'sum',
    'Total_No_of_Works_Takenup':'sum'
})

Aggregation performed at the state-year level for clearer trend analysis.
observed=False is specified to ensure all categories of state and year are considered, maintaining consistency with current pandas behavior.

In [36]:
df_state_year

,state_name,fin_year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,SC_persondays,...,Differently_abled_persons_worked,Material_and_skilled_Wages,Wages,Total_Adm_Expenditure,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,percentage_payments_generated_within_15_days,Number_of_Completed_Works,Number_of_Ongoing_Works,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup
0,ANDHRA PRADESH,2018-2019,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,"442,710,408.00",...,891439,"2,436,117.83","3,871,966.06","233,703.01",3592237,NaN,7418201,12939943,106834141,20358144
1,ANDHRA PRADESH,2019-2020,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,"369,949,160.00",...,844979,"319,077.57","3,524,078.25","253,758.91",2087661,NaN,3242356,13080184,108559734,16322540
2,ANDHRA PRADESH,2020-2021,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,"524,588,254.00",...,972955,"3,266,915.89","5,023,217.34","216,816.12",3835628,NaN,4482974,12258659,114077366,16741633
3,ANDHRA PRADESH,2021-2022,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,"541,695,880.00",...,946431,"2,081,208.88","4,903,852.16","117,673.85",3378122,99.51,3043444,9178351,118225169,12221795
4,ANDHRA PRADESH,2022-2023,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,"474,950,837.00",...,832637,"2,530,827.85","4,043,857.88","244,560.08",726747,100.00,1699459,12147706,82325514,13847165
5,ANDHRA PRADESH,2023-2024,"7,775,787.13","2,282,459,965.00",233.85,"50,668,853.00","81,071,537.00",42.47,2285400189,"522,423,212.00",...,880312,"2,046,673.66","5,504,731.81","224,381.66",2608725,99.98,4146140,10694937,81802413,14841077
6,ANDHRA PRADESH,2024-2025,"168,297,967.14","44,661,943,999.00",257.62,"1,205,233,355.00","1,897,062,189.00",38.52,49561620289,"10,901,544,848.00",...,20018130,"36,231,835.93","126,325,671.05","5,740,460.16",45059316,99.97,55708079,252563780,2050456086,308271859
7,ASSAM,2018-2019,"742,343.59","430,518,518.52",190.86,"11,542,195.00","16,109,133.00",19.95,287370855,"15,021,569.00",...,30921,"205,367.62","532,836.48","4,139.48",56216,92.78,461253,2255202,58639176,2716455
8,ASSAM,2019-2020,"876,214.36","416,001,356.00",184.75,"16,165,178.00","22,752,126.00",22.38,417181875,"21,413,774.00",...,47476,"82,744.15","792,440.35","1,029.86",85424,99.97,485493,2123052,63005399,2608545
9,ASSAM,2020-2021,"1,189,190.22","468,351,195.00",227.18,"16,731,922.00","23,051,322.00",22.40,468710817,"20,980,500.00",...,39980,"247,861.78","941,117.26",211.18,212827,97.79,808008,3145781,67660071,3953789
10,ASSAM,2021-2022,"1,354,216.56","561,856,633.59",207.26,"21,944,445.00","31,306,935.00",21.47,554970872,"23,214,164.00",...,56778,"148,027.99","1,195,954.73","10,233.84",161307,99.83,756376,5363664,74131985,6120040
11,ASSAM,2022-2023,"1,311,712.39","548,011,104.00",221.14,"20,455,078.00","29,765,624.00",23.61,547436612,"21,794,238.00",...,60309,"82,649.01","1,229,063.37",0.00,80167,99.92,1691115,9884303,80210947,11575418
12,ASSAM,2023-2024,"1,773,129.27","680,102,617.00",228.35,"20,215,134.00","29,966,445.00",30.63,677504655,"42,474,638.00",...,49203,"172,368.18","1,600,761.08",0.00,76935,99.82,4152619,11553355,82240713,15705974
13,ASSAM,2024-2025,"27,171,035.01","11,731,827,683.00",274.58,"314,535,871.00","424,634,253.00",24.88,9133118531,"509,660,714.00",...,631319,"4,333,901.52","22,837,133.49",0.00,1412084,99.68,103152753,139788410,1810131126,242941163
14,BIHAR,2018-2019,"1,914,057.62","885,657,013.00",159.14,"24,662,548.00","28,442,173.00",32.18,853986277,"174,561,757.00",...,51791,"478,573.15","1,423,970.65","11,513.82",100031,NaN,1160561,15261511,208998086,16422072
15,BIHAR,2019-2020,"2,076,248.13","1,230,958,080.00",162.39,"26,295,908.00","30,082,406.00",33.32,950339921,"160,452,873.00",...,56214,"466,772.65","1,594,355.09","15,120.39",77242,99.80,3000679,20963120,223666985,23963799
16,BIHAR,2020-2021,"4,501,876.51","1,568,042,356.00",169.38,"42,937,705.00","48,854,620.00",33.12,1558584369,"186,079,188.00",...,82414,"1,634,045.26","2,827,465.30","40,365.95",120709,99.75,5796765,27841649,249011783,33638414
17,BIHAR,2021-2022,"5,156,343.02","1,712,238,715.00",188.89,"38,233,107.00","42,771,176.00",30.99,1247435841,"143,201,558.00",...,69266,"2,689,453.01","2,430,578.68","36,311.33",78725,99.99,9373921,19496731,250281386,28870652
18,BIHAR,2022-2023,"4,831,906.86","1,970,297,228.00",198.41,"47,162,125.00","53,942,143.00",38.01,1899344359,"334,264,840.00",...,82957,"865,253.88","3,922,115.39","44,537.59",195894,99.99,7136822,17317093,172973117,24453915
19,BIHAR,2023-2024,"5,333,677.22","1,782,608,341.00",214.47,"44,151,908.00","49,196,734.00",34.64,1621993525,"291,986,591.00",...,87516,"1,687,683.88","3,604,577.72","41,415.62",144476,99.95,4920441,11061116,163399525,15981557
20,BIHAR,2024-2025,"113,305,713.32","35,883,303,342.00",487.42,"872,654,424.00","955,102,502.00",34.41,33146223044,"6,547,924,824.00",...,1476599,"30,417,918.14","81,867,323.30","1,020,471.89",2405862,99.92,49849930,216631396,3738275828,266481326
21,MADHYA PRADESH,2018-2019,"3,498,582.23","1,497,000,000.00",153.74,"32,421,207.00","52,895,332.00",36.68,1307284018,"218,217,105.00",...,454938,"1,397,518.26","2,101,060.88",3.08,293709,NaN,8235136,12039206,95149443,20274342
22,MADHYA PRADESH,2019-2020,"3,128,439.16","1,514,000,000.00",159.72,"31,504,035.00","51,690,828.00",40.88,1367262882,"193,699,467.00",...,456641,"889,446.63","2,238,992.53",0.00,435176,99.81,3556719,8397855,96831485,11954574
23,MADHYA PRADESH,2020-2021,"5,388,680.74","2,510,663,081.00",157.85,"47,091,038.00","85,484,316.00",43.14,2308339300,"311,737,808.00",...,708522,"1,423,577.22","3,965,103.51",0.00,1378526,99.84,5062002,10726572,105735132,15788574
24,MADHYA PRADESH,2021-2022,"5,963,837.25","2,317,623,385.00",173.81,"49,059,357.00","88,106,338.00",44.69,2321353600,"293,939,274.00",...,662130,"1,803,105.63","4,139,988.29","20,743.33",1042731,99.83,3945330,16533549,109760158,20478879
25,MADHYA PRADESH,2022-2023,"5,627,355.14","1,749,666,701.00",185.97,"41,759,062.00","68,672,395.00",39.01,1748454525,"242,185,899.00",...,550471,"2,033,902.18","3,356,114.17","237,338.79",530132,99.89,6861939,17295327,106199201,24157266
26,MADHYA PRADESH,2023-2024,"4,754,852.30","1,675,999,990.00",192.75,"35,510,491.00","54,226,339.00",34.52,1372118507,"173,386,131.00",...,465756,"1,688,807.86","2,785,153.45","280,890.98",366995,99.89,5537681,10774390,104625536,16312071
27,MADHYA PRADESH,2024-2025,"86,166,156.49","29,955,774,773.00",232.79,"637,582,407.00","919,140,841.00",33.30,23281398290,"2,914,006,710.00",...,7657461,"25,109,982.41","53,918,758.79","7,137,415.29",4572116,99.82,55145983,153916561,2214550330,209062544
28,MAHARASHTRA,2018-2019,"1,564,196.31","667,080,232.00",182.99,"15,895,479.00","28,539,042.00",33.21,604458736,"63,786,119.00",...,181727,"395,206.93","1,111,686.19","57,303.19",1057996,99.83,2177777,7690788,110499250,9868565
29,MAHARASHTRA,2019-2020,"1,203,799.29","650,000,000.00",193.15,"13,117,998.00","23,015,624.00",31.09,451238673,"50,577,218.00",...,142610,"277,831.66","869,382.47","56,585.16",749547,99.87,2243556,7494104,113463169,9737660
30,MAHARASHTRA,2020-2021,"1,154,213.34","487,495,006.00",201.98,"13,670,312.00","24,767,253.00",28.95,439272399,"39,577,432.00",...,151945,"179,917.16","915,746.46","58,549.72",705662,99.84,1736173,8421114,119549140,10157287
31,MAHARASHTRA,2021-2022,"1,330,097.08","651,299,992.00",231.01,"15,591,931.00","27,576,639.00",26.13,458217105,"40,593,157.00",...,129568,"236,378.63","1,065,973.59","27,744.86",737296,99.88,1551697,10256689,143871981,11808386
32,MAHARASHTRA,2022-2023,"2,014,621.40","539,065,535.00",234.30,"18,925,599.00","32,984,537.00",27.39,601328867,"47,798,765.00",...,161057,"540,147.31","1,422,020.43","52,453.67",855411,99.78,2252629,11464443,154890615,13717072
33,MAHARASHTRA,2023-2024,"2,422,188.81","632,746,398.00",257.40,"19,497,730.00","32,384,633.00",27.80,667693571,"51,072,250.00",...,150344,"683,131.31","1,685,785.94","53,271.57",1191340,99.83,2205496,11577854,161248445,13783350
34,MAHARASHTRA,2024-2025,"82,611,962.17","17,802,731,312.00",298.56,"550,649,946.00","909,245,986.00",33.48,21956416221,"1,407,420,878.00",...,4512619,"17,767,081.51","62,597,520.53","2,247,360.13",42577832,99.57,50758899,278349424,3809230573,329108323
35,RAJASTHAN,2018-2019,"3,725,431.87","1,651,072,397.00",121.08,"41,482,808.00","58,349,442.00",36.21,1736363862,"388,563,365.00",...,152171,"1,384,983.58","2,216,319.76","124,128.53",1148909,100.00,2720960,7487774,122445750,10208734
36,RAJASTHAN,2019-2020,"4,664,133.39","2,523,692,764.00",138.27,"55,381,000.00","77,105,423.00",44.12,2632974104,"593,382,888.00",...,212280,"615,067.13","3,753,199.48","295,866.78",3034842,99.99,2528486,6893087,127719156,9421573
37,RAJASTHAN,2020-2021,"6,518,923.24","3,111,083,009.00",142.61,"72,706,979.00","102,127,342.00",40.64,3356622758,"732,665,076.00",...,293610,"988,326.76","5,214,331.32","316,265.16",3510384,99.97,2511223,8602388,137349755,11113611
38,RAJASTHAN,2021-2022,"7,057,129.99","2,678,688,020.00",167.48,"64,568,214.00","87,546,285.00",36.46,2786292953,"566,742,654.00",...,270904,"1,794,034.36","4,902,361.36","360,734.27",2912595,99.94,2201763,8729115,142644873,10930878
39,RAJASTHAN,2022-2023,"6,337,027.88","2,312,524,935.00",174.66,"58,059,813.00","77,704,225.00",37.03,2420379115,"506,362,202.00",...,273496,"1,852,167.29","4,373,731.72","111,128.87",1505011,99.93,2389524,10085019,138022386,12474543
40,RAJASTHAN,2023-2024,"5,917,484.31","2,367,920,856.00",187.94,"59,311,512.00","78,090,432.00",37.77,2599098265,"521,142,980.00",...,282626,"786,371.40","5,047,976.84","83,136.08",1227180,99.93,1998523,8157662,136579125,10156185
41,RAJASTHAN,2024-2025,"149,660,506.04","50,832,253,843.00","2,902.65","1,198,420,370.00","1,517,084,682.00",33.68,47579932017,"9,620,823,927.00",...,5682893,"42,053,819.32","104,608,918.30","2,997,768.42",24030863,99.61,49822101,162772046,3108908974,212594147

In [37]:
df_state_year.shape

(42, 22)

### CREATING REGION-YEAR AGGREGATED DATASET

Region-Year aggregation means grouping states into their respective regions, then aggregating metrics per region per year.
It gives metrics at region level per year, allowing regional comparison and trend analysis.

In [54]:
# Mapping states to regions
state_to_region = {
    'ANDHRA PRADESH': 'South',
    'RAJASTHAN': 'North',
    'BIHAR': 'East',
    'ASSAM': 'Northeast',
    'MAHARASHTRA': 'West',
    'MADHYA PRADESH': 'Central'
}

# Add region column
df_state_year['region'] = df_state_year['state_name'].map(state_to_region)

In [56]:
# Region-year aggregation
df_region_year = df_state_year.groupby(['region','fin_year'], as_index=False,observed=False).agg({
    'Total_Exp':'sum',
    'Approved_Labour_Budget':'sum',
    'Average_Wage_rate_per_day_per_person':'mean',
    'Total_Households_Worked':'sum',
    'Total_Individuals_Worked':'sum',
    'Average_days_of_employment_provided_per_Household':'mean',
    'Persondays_of_Central_Liability_so_far':'sum',
    'SC_persondays':'sum',
    'ST_persondays':'sum',
    'Women_Persondays':'sum',
    'Differently_abled_persons_worked':'sum',
    'Material_and_skilled_Wages':'sum',
    'Wages':'sum',
    'Total_Adm_Expenditure':'sum',
    'Total_No_of_HHs_completed_100_Days_of_Wage_Employment':'sum',
    'percentage_payments_generated_within_15_days':'mean',
    # Operational performance indicators
    'Number_of_Completed_Works':'sum',
    'Number_of_Ongoing_Works':'sum',
    'Total_No_of_JobCards_issued':'sum',
    'Total_No_of_Works_Takenup':'sum'
})

This dataset contains Financial, employment, inclusiveness, administrative efficiency metrics and Operational performance metrics.

In [57]:
df_region_year.head()

,region,fin_year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,SC_persondays,...,Differently_abled_persons_worked,Material_and_skilled_Wages,Wages,Total_Adm_Expenditure,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,percentage_payments_generated_within_15_days,Number_of_Completed_Works,Number_of_Ongoing_Works,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup
0,South,2018-2019,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,"442,710,408.00",...,891439,"2,436,117.83","3,871,966.06","233,703.01",3592237,NaN,7418201,12939943,106834141,20358144
1,South,2019-2020,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,"369,949,160.00",...,844979,"319,077.57","3,524,078.25","253,758.91",2087661,NaN,3242356,13080184,108559734,16322540
2,South,2020-2021,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,"524,588,254.00",...,972955,"3,266,915.89","5,023,217.34","216,816.12",3835628,NaN,4482974,12258659,114077366,16741633
3,South,2021-2022,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,"541,695,880.00",...,946431,"2,081,208.88","4,903,852.16","117,673.85",3378122,99.51,3043444,9178351,118225169,12221795
4,South,2022-2023,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,"474,950,837.00",...,832637,"2,530,827.85","4,043,857.88","244,560.08",726747,100.00,1699459,12147706,82325514,13847165

In [58]:
df_region_year.shape

(42, 22)

### CREATING TIME VARIABLE FOR TREND PLOTS

The original fin_year column is text (string).
Many analysis tasks need numeric time values, such as:
-Trend Analysis
-Line Graphs
-Growth Rate Calculations

In [60]:
df_clean['year'] = df_clean['fin_year'].str[:4].astype(int)

In [61]:
df_state_year['year'] = df_state_year['fin_year'].str[:4].astype(int)

In [62]:
df_region_year['year'] = df_state_year['fin_year'].str[:4].astype(int)

.str[:4] extracts the first four characters (the starting year).
.astype(int) converts it into a numeric variable useful for trend plots.

#### CHECKING THE VARIABLE CREATED

In [44]:
df_clean[['fin_year','year']].head()

    fin_year  year
0  2018-2019  2018
1  2018-2019  2018
2  2018-2019  2018
3  2018-2019  2018
4  2018-2019  2018

In [45]:
df_clean.shape

(72572, 36)

In [46]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72572 entries, 0 to 72575
Data columns (total 36 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   fin_year                                               72572 non-null  category
 1   month                                                  49227 non-null  category
 2   state_code                                             72572 non-null  int64
 3   state_name                                             72572 non-null  category
 4   district_code                                          72572 non-null  int64
 5   district_name                                          72572 non-null  category
 6   Approved_Labour_Budget                                 72572 non-null  float64
 7   Average_Wage_rate_per_day_per_person                   72572 non-null  float64
 8   Average_days_of_employment_provided_per_Household      72572 non-null  int64
 9   Differently_abled_persons_worked                       72572 non-null  int64
 10  Material_and_skilled_Wages                             72572 non-null  float64
 11  Number_of_Completed_Works                              72572 non-null  int64
 12  Number_of_GPs_with_NIL_exp                             72572 non-null  int64
 13  Number_of_Ongoing_Works                                72572 non-null  int64
 14  Persondays_of_Central_Liability_so_far                 72572 non-null  int64
 15  SC_persondays                                          72572 non-null  float64
 16  SC_workers_against_active_workers                      72572 non-null  int64
 17  ST_persondays                                          72572 non-null  float64
 18  ST_workers_against_active_workers                      72572 non-null  int64
 19  Total_Adm_Expenditure                                  72572 non-null  float64
 20  Total_Exp                                              72572 non-null  float64
 21  Total_Households_Worked                                72572 non-null  float64
 22  Total_Individuals_Worked                               72572 non-null  float64
 23  Total_No_of_Active_Job_Cards                           72572 non-null  int64
 24  Total_No_of_Active_Workers                             72572 non-null  int64
 25  Total_No_of_HHs_completed_100_Days_of_Wage_Employment  72572 non-null  int64
 26  Total_No_of_JobCards_issued                            72572 non-null  int64
 27  Total_No_of_Workers                                    72572 non-null  float64
 28  Total_No_of_Works_Takenup                              72572 non-null  int64
 29  Wages                                                  72572 non-null  float64
 30  Women_Persondays                                       72572 non-null  float64
 31  percent_of_Category_B_Works                            72572 non-null  int64
 32  percent_of_Expenditure_on_Agriculture_Allied_Works     72572 non-null  float64
 33  percent_of_NRM_Expenditure                             72572 non-null  float64
 34  percentage_payments_generated_within_15_days           43113 non-null  float64
 35  year                                                   72572 non-null  int64
dtypes: category(4), float64(15), int64(17)
memory usage: 18.6 MB

In [47]:
df_state_year.head()

,state_name,fin_year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,SC_persondays,...,Wages,Total_Adm_Expenditure,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,percentage_payments_generated_within_15_days,Number_of_Completed_Works,Number_of_Ongoing_Works,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup,region,year
0,ANDHRA PRADESH,2018-2019,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,"442,710,408.00",...,"3,871,966.06","233,703.01",3592237,NaN,7418201,12939943,106834141,20358144,NaN,2018
1,ANDHRA PRADESH,2019-2020,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,"369,949,160.00",...,"3,524,078.25","253,758.91",2087661,NaN,3242356,13080184,108559734,16322540,NaN,2019
2,ANDHRA PRADESH,2020-2021,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,"524,588,254.00",...,"5,023,217.34","216,816.12",3835628,NaN,4482974,12258659,114077366,16741633,NaN,2020
3,ANDHRA PRADESH,2021-2022,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,"541,695,880.00",...,"4,903,852.16","117,673.85",3378122,99.51,3043444,9178351,118225169,12221795,NaN,2021
4,ANDHRA PRADESH,2022-2023,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,"474,950,837.00",...,"4,043,857.88","244,560.08",726747,100.00,1699459,12147706,82325514,13847165,NaN,2022

In [48]:
df_clean.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_generated_within_15_days,year
0,2018-2019,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,"15,623,529.00",198.18,48,10878,...,519227,"1,218,221.00",130223,"34,032.16","10,985,218.00",57,76.08,74.11,NaN,2018
1,2018-2019,Nov,2,ANDHRA PRADESH,209,NELLORE,"10,931,309.00",201.46,50,3235,...,615947,"1,261,092.00",142535,"23,643.54","7,152,274.00",64,64.26,61.55,NaN,2018
2,2018-2019,Nov,2,ANDHRA PRADESH,211,Y.S.R,"9,831,635.00",206.47,59,4022,...,567546,"1,164,238.00",137615,"27,883.61","8,591,158.00",68,70.41,73.29,NaN,2018
3,2018-2019,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,"17,114,336.00",197.73,46,9108,...,577694,"1,309,583.00",89937,"33,824.03","11,557,724.00",60,77.73,77.34,NaN,2018
4,2018-2019,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,"14,897,034.00",196.61,46,10772,...,517720,"1,217,417.00",120755,"32,315.22","10,553,260.00",55,80.80,79.72,NaN,2018

In [63]:
df_region_year.head()

,region,fin_year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,SC_persondays,...,Material_and_skilled_Wages,Wages,Total_Adm_Expenditure,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,percentage_payments_generated_within_15_days,Number_of_Completed_Works,Number_of_Ongoing_Works,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup,year
0,South,2018-2019,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,"442,710,408.00",...,"2,436,117.83","3,871,966.06","233,703.01",3592237,NaN,7418201,12939943,106834141,20358144,2018
1,South,2019-2020,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,"369,949,160.00",...,"319,077.57","3,524,078.25","253,758.91",2087661,NaN,3242356,13080184,108559734,16322540,2019
2,South,2020-2021,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,"524,588,254.00",...,"3,266,915.89","5,023,217.34","216,816.12",3835628,NaN,4482974,12258659,114077366,16741633,2020
3,South,2021-2022,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,"541,695,880.00",...,"2,081,208.88","4,903,852.16","117,673.85",3378122,99.51,3043444,9178351,118225169,12221795,2021
4,South,2022-2023,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,"474,950,837.00",...,"2,530,827.85","4,043,857.88","244,560.08",726747,100.00,1699459,12147706,82325514,13847165,2022

### REORDERING COLUMN

For better readability in the project, reordering column so that 'year' appears next to 'fin_year'

In [49]:
col_index = df_clean.columns.get_loc('fin_year')
df_clean.insert(col_index + 1, 'year', df_clean.pop('year'))

In [66]:
col_index = df_state_year.columns.get_loc('fin_year')
df_state_year.insert(col_index + 1, 'year', df_state_year.pop('year'))

#removing region column from df_state_year
df_state_year = df_state_year.drop(columns=['region'])

In [64]:
col_index = df_region_year.columns.get_loc('fin_year')
df_region_year.insert(col_index + 1, 'year', df_region_year.pop('year'))

df.pop('year') removes the column and returns it
df.insert() inserts it at the desired position

In [51]:
df_clean.head()

,fin_year,year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,...,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_generated_within_15_days
0,2018-2019,2018,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,"15,623,529.00",198.18,48,...,14672,519227,"1,218,221.00",130223,"34,032.16","10,985,218.00",57,76.08,74.11,NaN
1,2018-2019,2018,Nov,2,ANDHRA PRADESH,209,NELLORE,"10,931,309.00",201.46,50,...,27632,615947,"1,261,092.00",142535,"23,643.54","7,152,274.00",64,64.26,61.55,NaN
2,2018-2019,2018,Nov,2,ANDHRA PRADESH,211,Y.S.R,"9,831,635.00",206.47,59,...,40799,567546,"1,164,238.00",137615,"27,883.61","8,591,158.00",68,70.41,73.29,NaN
3,2018-2019,2018,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,"17,114,336.00",197.73,46,...,12019,577694,"1,309,583.00",89937,"33,824.03","11,557,724.00",60,77.73,77.34,NaN
4,2018-2019,2018,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,"14,897,034.00",196.61,46,...,10794,517720,"1,217,417.00",120755,"32,315.22","10,553,260.00",55,80.80,79.72,NaN

In [67]:
df_state_year.head()

,state_name,fin_year,year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,...,Differently_abled_persons_worked,Material_and_skilled_Wages,Wages,Total_Adm_Expenditure,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,percentage_payments_generated_within_15_days,Number_of_Completed_Works,Number_of_Ongoing_Works,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup
0,ANDHRA PRADESH,2018-2019,2018,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,...,891439,"2,436,117.83","3,871,966.06","233,703.01",3592237,NaN,7418201,12939943,106834141,20358144
1,ANDHRA PRADESH,2019-2020,2019,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,...,844979,"319,077.57","3,524,078.25","253,758.91",2087661,NaN,3242356,13080184,108559734,16322540
2,ANDHRA PRADESH,2020-2021,2020,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,...,972955,"3,266,915.89","5,023,217.34","216,816.12",3835628,NaN,4482974,12258659,114077366,16741633
3,ANDHRA PRADESH,2021-2022,2021,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,...,946431,"2,081,208.88","4,903,852.16","117,673.85",3378122,99.51,3043444,9178351,118225169,12221795
4,ANDHRA PRADESH,2022-2023,2022,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,...,832637,"2,530,827.85","4,043,857.88","244,560.08",726747,100.00,1699459,12147706,82325514,13847165

In [68]:
df_region_year.head()

,region,fin_year,year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,...,Differently_abled_persons_worked,Material_and_skilled_Wages,Wages,Total_Adm_Expenditure,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,percentage_payments_generated_within_15_days,Number_of_Completed_Works,Number_of_Ongoing_Works,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup
0,South,2018-2019,2018,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,...,891439,"2,436,117.83","3,871,966.06","233,703.01",3592237,NaN,7418201,12939943,106834141,20358144
1,South,2019-2020,2019,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,...,844979,"319,077.57","3,524,078.25","253,758.91",2087661,NaN,3242356,13080184,108559734,16322540
2,South,2020-2021,2020,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,...,972955,"3,266,915.89","5,023,217.34","216,816.12",3835628,NaN,4482974,12258659,114077366,16741633
3,South,2021-2022,2021,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,...,946431,"2,081,208.88","4,903,852.16","117,673.85",3378122,99.51,3043444,9178351,118225169,12221795
4,South,2022-2023,2022,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,...,832637,"2,530,827.85","4,043,857.88","244,560.08",726747,100.00,1699459,12147706,82325514,13847165

### FEATURE ENGINEERING

Feature engineering focuses on creating new derived variables that capture performance ratios, percentages, and standardized indicators.

#### 1. EXPENDITURE PER HOUSEHOLD

In [69]:
df_region_year['exp_per_household'] = df_region_year['Total_Exp'] / df_region_year['Total_Households_Worked']

#### 2. WAGE SHARE RATIO

In [70]:
df_region_year['wage_share_ratio'] = df_region_year['Wages'] / df_region_year['Total_Exp']

#### 3. SC/ST PARTICIPATION PERCENTAGE

In [72]:
df_region_year['sc_participation_percent'] = df_region_year['SC_persondays'] / df_region_year['Persondays_of_Central_Liability_so_far'] * 100
df_region_year['st_participation_percent'] = df_region_year['ST_persondays'] / df_region_year['Persondays_of_Central_Liability_so_far'] * 100

#### 4. WOMEN PARTICIPATION RATIO

In [73]:
df_region_year['women_participation_ratio'] = df_region_year['Women_Persondays'] / df_region_year['Persondays_of_Central_Liability_so_far'] * 100

#### 5. DIFFERENTLY-ABLED PARTICIPATION RATIO

In [74]:
df_region_year['diff_abled_participation_ratio'] = df_region_year['Differently_abled_persons_worked'] / df_region_year['Total_Individuals_Worked'] * 100

#### 6. EMPLOYMENT FULFILLMENT RATIO

In [75]:
df_region_year['employment_fulfillment_ratio'] = df_region_year['Average_days_of_employment_provided_per_Household'] / 100

#### 7. LABOUR BUDGET UTILIZATION RATIO

In [80]:
df_region_year['labour_budget_utilization_ratio'] = df_region_year['Total_Exp'] / df_region_year['Approved_Labour_Budget']

### VERIFYING THE DATASETS

In [82]:
print(df_clean.shape)
print(df_state_year.shape)
print(df_region_year.shape)

# df_region_year contains Regional performance indicators + feature engineering

(72572, 36)
(42, 23)
(42, 31)

In [83]:
df_clean.head()

,fin_year,year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,...,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_generated_within_15_days
0,2018-2019,2018,Nov,2,ANDHRA PRADESH,202,VIZIANAGARAM,"15,623,529.00",198.18,48,...,14672,519227,"1,218,221.00",130223,"34,032.16","10,985,218.00",57,76.08,74.11,NaN
1,2018-2019,2018,Nov,2,ANDHRA PRADESH,209,NELLORE,"10,931,309.00",201.46,50,...,27632,615947,"1,261,092.00",142535,"23,643.54","7,152,274.00",64,64.26,61.55,NaN
2,2018-2019,2018,Nov,2,ANDHRA PRADESH,211,Y.S.R,"9,831,635.00",206.47,59,...,40799,567546,"1,164,238.00",137615,"27,883.61","8,591,158.00",68,70.41,73.29,NaN
3,2018-2019,2018,Sep,2,ANDHRA PRADESH,201,SRIKAKULAM,"17,114,336.00",197.73,46,...,12019,577694,"1,309,583.00",89937,"33,824.03","11,557,724.00",60,77.73,77.34,NaN
4,2018-2019,2018,Sep,2,ANDHRA PRADESH,202,VIZIANAGARAM,"14,897,034.00",196.61,46,...,10794,517720,"1,217,417.00",120755,"32,315.22","10,553,260.00",55,80.80,79.72,NaN

In [84]:
df_state_year.head()

,state_name,fin_year,year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,...,Differently_abled_persons_worked,Material_and_skilled_Wages,Wages,Total_Adm_Expenditure,Total_No_of_HHs_completed_100_Days_of_Wage_Employment,percentage_payments_generated_within_15_days,Number_of_Completed_Works,Number_of_Ongoing_Works,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup
0,ANDHRA PRADESH,2018-2019,2018,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,...,891439,"2,436,117.83","3,871,966.06","233,703.01",3592237,NaN,7418201,12939943,106834141,20358144
1,ANDHRA PRADESH,2019-2020,2019,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,...,844979,"319,077.57","3,524,078.25","253,758.91",2087661,NaN,3242356,13080184,108559734,16322540
2,ANDHRA PRADESH,2020-2021,2020,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,...,972955,"3,266,915.89","5,023,217.34","216,816.12",3835628,NaN,4482974,12258659,114077366,16741633
3,ANDHRA PRADESH,2021-2022,2021,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,...,946431,"2,081,208.88","4,903,852.16","117,673.85",3378122,99.51,3043444,9178351,118225169,12221795
4,ANDHRA PRADESH,2022-2023,2022,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,...,832637,"2,530,827.85","4,043,857.88","244,560.08",726747,100.00,1699459,12147706,82325514,13847165

In [85]:
df_region_year.head()

,region,fin_year,year,Total_Exp,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Total_Households_Worked,Total_Individuals_Worked,Average_days_of_employment_provided_per_Household,Persondays_of_Central_Liability_so_far,...,Total_No_of_JobCards_issued,Total_No_of_Works_Takenup,exp_per_household,wage_share_ratio,sc_participation_percent,st_participation_percent,women_participation_ratio,diff_abled_participation_ratio,employment_fulfillment_ratio,labour_budget_utilization_ratio
0,South,2018-2019,2018,"6,541,786.91","1,784,696,720.00",188.29,"45,499,088.00","72,855,369.00",41.89,2001342599,...,106834141,20358144,0.14,0.59,22.12,9.89,59.71,1.22,0.42,0.00
1,South,2019-2020,2019,"4,096,914.73","1,786,520,154.00",197.52,"43,799,701.00","69,356,921.00",37.24,1726846511,...,108559734,16322540,0.09,0.86,21.42,10.98,59.87,1.22,0.37,0.00
2,South,2020-2021,2020,"8,506,949.35","2,267,775,830.00",209.22,"52,086,231.00","85,967,921.00",40.56,2268594364,...,114077366,16741633,0.16,0.59,23.12,10.97,56.61,1.13,0.41,0.00
3,South,2021-2022,2021,"7,102,734.89","2,325,682,437.00",205.42,"52,033,029.00","84,802,845.00",42.60,2306204647,...,118225169,12221795,0.14,0.69,23.49,10.05,57.52,1.12,0.43,0.00
4,South,2022-2023,2022,"6,819,245.81","2,001,549,532.00",196.89,"48,516,567.00","79,087,365.00",38.97,2011127903,...,82325514,13847165,0.14,0.59,23.62,9.64,60.01,1.05,0.39,0.00

### CHECKING FOR MISSING VALUES

In [87]:
df_state_year.isnull().sum()

state_name                                               0
fin_year                                                 0
year                                                     0
Total_Exp                                                0
Approved_Labour_Budget                                   0
Average_Wage_rate_per_day_per_person                     0
Total_Households_Worked                                  0
Total_Individuals_Worked                                 0
Average_days_of_employment_provided_per_Household        0
Persondays_of_Central_Liability_so_far                   0
SC_persondays                                            0
ST_persondays                                            0
Women_Persondays                                         0
Differently_abled_persons_worked                         0
Material_and_skilled_Wages                               0
Wages                                                    0
Total_Adm_Expenditure                                    0
Total_No_of_HHs_completed_100_Days_of_Wage_Employment    0
percentage_payments_generated_within_15_days             5
Number_of_Completed_Works                                0
Number_of_Ongoing_Works                                  0
Total_No_of_JobCards_issued                              0
Total_No_of_Works_Takenup                                0
dtype: int64

In [88]:
df_region_year.isnull().sum()

region                                                   0
fin_year                                                 0
year                                                     0
Total_Exp                                                0
Approved_Labour_Budget                                   0
Average_Wage_rate_per_day_per_person                     0
Total_Households_Worked                                  0
Total_Individuals_Worked                                 0
Average_days_of_employment_provided_per_Household        0
Persondays_of_Central_Liability_so_far                   0
SC_persondays                                            0
ST_persondays                                            0
Women_Persondays                                         0
Differently_abled_persons_worked                         0
Material_and_skilled_Wages                               0
Wages                                                    0
Total_Adm_Expenditure                                    0
Total_No_of_HHs_completed_100_Days_of_Wage_Employment    0
percentage_payments_generated_within_15_days             5
Number_of_Completed_Works                                0
Number_of_Ongoing_Works                                  0
Total_No_of_JobCards_issued                              0
Total_No_of_Works_Takenup                                0
exp_per_household                                        0
wage_share_ratio                                         0
sc_participation_percent                                 0
st_participation_percent                                 0
women_participation_ratio                                0
diff_abled_participation_ratio                           0
employment_fulfillment_ratio                             0
labour_budget_utilization_ratio                          0
dtype: int64

This ensures feature engineering and aggregation worked correctly.

### SAVING THE DATASETS

In [98]:
# Saving the datasets directly into the processed folder inside data folder 
df_clean.to_csv("../data/processed/mgnrega_clean_dataset.csv", index=False)

df_state_year.to_csv("../data/processed/mgnrega_state_year_dataset.csv", index=False)

df_region_year.to_csv("../data/processed/mgnrega_region_year_dataset.csv", index=False)

### VERIFYING THE DATSETS

In [99]:
os.listdir("../data/processed")

['mgnrega_clean_dataset.csv',
 'mgnrega_region_year_dataset.csv',
 'mgnrega_state_year_dataset.csv']